name: Check Kubernetes manifest

on:
  workflow_dispatch:

jobs:
  run_check_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip && pip install openai

      - name: Run the validation script
        id: validate_manifest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python demo02-CheckK8sManifest/check-man.py -f demo02-CheckK8sManifest/manifest-to-check.yaml
      
      - name: Deploy manifest if valid
        if: steps.validate_manifest.outputs.validation_result == 'The manifest is valid'
        run: |
          echo "Mock deployment to Kubernetes cluster"

      - name: Deploy manifest if valid
        if: steps.validate_manifest.outputs.validation_result == 'The manifest is not valid'
        run: |
          echo "ERROR: manifest is not valid!"

