name: Generate Reports

on:
  workflow_dispatch:

jobs:
  run_check_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install openai

      - name: Run the generation script
        id: generate_reports
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python demo03-createReports/create-report.py -f demo03-createReports/incident.txt

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: incident_documents
      
