name: Generate Terraform File

on:
  workflow_dispatch:

jobs:
  run_check_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install openai

      - name: Run the validation script
        id: validate_manifest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python demo01-GenerateTF/generate-tf.py -f demo01-GenerateTF/tf-spec.txt

      - name: Upload Terraform configuration
        uses: actions/upload-artifact@v4
        with:
          name: terraform-config
          path: main.tf
      
