name: Generate Terraform File

on:
  workflow_dispatch:

jobs:
  run_check_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install openai

      - name: Run the generation script
        id: generate_tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python demo04-createTests/create-test.py -f demo04-createTests/api_spec.txt

      - name: Upload Tests
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: test_api_server.py
      
